### **Pytorch Fundamental**

In [38]:
!nvidia-smi

Wed Sep 11 16:20:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0              30W /  70W |    151MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [39]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [40]:
torch.cuda.is_available()

True

In [41]:
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [42]:
torch.cuda.device_count()

1

## **Day 5**

In [43]:
tensor =torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [44]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [45]:
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## **Exercise**

In [46]:
#create random tensor with shape (7,7)
tensor_rand=torch.rand(7,7)
tensor_rand

tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071],
        [0.6297, 0.3653, 0.8513, 0.8549, 0.5509, 0.2868, 0.2063],
        [0.4451, 0.3593, 0.7204, 0.0731, 0.9699, 0.1078, 0.8829],
        [0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286],
        [0.7653, 0.1132, 0.8559, 0.6721, 0.6267, 0.5691, 0.7437],
        [0.9592, 0.3887, 0.2214, 0.3742, 0.1953, 0.7405, 0.2529],
        [0.2332, 0.9314, 0.9575, 0.5575, 0.4134, 0.4355, 0.7369]])

In [47]:
#multiply
tensor_17=torch.rand(1,7)
mul=torch.matmul(tensor_rand, tensor_17.T)
mul, mul.shape

(tensor([[1.5419],
         [2.0645],
         [1.6890],
         [1.9196],
         [2.2098],
         [0.9377],
         [2.1266]]),
 torch.Size([7, 1]))

In [48]:
#Random_seed=0
random_seed=0
generator = torch.Generator().manual_seed(random_seed) #*
tensor_rand=torch.rand((7,7))
tensor_rand

tensor([[0.2674, 0.4990, 0.7447, 0.7213, 0.4414, 0.5550, 0.6361],
        [0.1081, 0.3305, 0.5196, 0.2147, 0.2816, 0.6679, 0.7878],
        [0.5070, 0.3055, 0.7738, 0.2259, 0.3826, 0.9717, 0.5921],
        [0.5352, 0.6686, 0.3781, 0.9278, 0.0922, 0.3625, 0.4136],
        [0.2943, 0.3762, 0.8099, 0.7743, 0.5278, 0.9356, 0.1470],
        [0.2019, 0.7259, 0.4731, 0.0444, 0.1539, 0.1956, 0.8861],
        [0.7264, 0.8868, 0.1278, 0.0125, 0.1721, 0.5535, 0.4012]])

In [49]:
tensor_rand2=torch.rand((1,7))
mul=torch.matmul(tensor_rand,tensor_rand2.T)
mul, mul.shape

(tensor([[1.9311],
         [1.6216],
         [1.7869],
         [1.5387],
         [1.6650],
         [1.7436],
         [1.6029]]),
 torch.Size([7, 1]))

In [50]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [51]:
#ex-6
torch.cuda.manual_seed(1234)
ran1=torch.rand(2,3)
ran2=torch.rand(2,3)
ran1=ran1.to(device)
ran2=ran2.to(device)
print(ran1, ran2)

tensor([[0.6192, 0.5123, 0.6050],
        [0.1243, 0.2325, 0.2650]], device='cuda:0') tensor([[0.2171, 0.5887, 0.5999],
        [0.2923, 0.8259, 0.2218]], device='cuda:0')


In [52]:
#ex-7
mul=torch.matmul(ran1,ran2.T)
mul

tensor([[0.7989, 0.7383],
        [0.3228, 0.2871]], device='cuda:0')

In [53]:
#ex-8
mul.max(), mul.min()

(tensor(0.7989, device='cuda:0'), tensor(0.2871, device='cuda:0'))

In [54]:
#ex-9
mul.argmax(), mul.argmin()

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [55]:
#ex-10
random_seed=7
tensor=torch.rand(1,1,1,10)
torch.manual_seed(random_seed)
new_tensor=tensor[0][0][0][:]
new_tensor, new_tensor.size

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

(tensor([0.6009, 0.3572, 0.0663, 0.1744, 0.7042, 0.6979, 0.1908, 0.3441, 0.0326,
         0.7688]),
 <function Tensor.size>)