### **Pytorch Fundamental**

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


## **Day 4**

In [3]:
# Indexing
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
# Index on middle bracket (dim1)
x[0][0]

tensor([1, 2, 3])

In [7]:
# Index the inner bracket
x[0][2][2]

tensor(9)

In [8]:
# Use ":" to select "all"
x[:,0]

tensor([[1, 2, 3]])

In [9]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [24]:
# numpy to tensor
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [26]:
array =array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [27]:
# tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [28]:
# change tensor
tensor= tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [29]:
torch.rand(3,3)

tensor([[0.1136, 0.1492, 0.5735],
        [0.3554, 0.2590, 0.9968],
        [0.0287, 0.5842, 0.3829]])

In [45]:
randA= torch.rand(3,3)
randB= torch.rand(3,3)

print(randA)
print(randB)
print(randA==randB)

tensor([[0.9400, 0.7412, 0.4593],
        [0.2739, 0.3005, 0.4471],
        [0.5555, 0.6217, 0.1865]])
tensor([[0.2709, 0.5493, 0.1558],
        [0.7502, 0.4345, 0.4625],
        [0.6038, 0.8598, 0.8795]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [46]:
random_seed=42
torch.manual_seed(random_seed)
randC=torch.rand(3,3)

torch.manual_seed(random_seed)
randD=torch.rand(3,3)

print(randC)
print(randD)
print(randC==randD)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
