### **Pytorch Fundamental**

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


## **Day 3**

In [3]:
ma1=torch.rand(3,4)
ma2=torch.rand(4,3)

In [6]:
# Matrix Multiply
multi=torch.matmul(ma1,ma2)
multi.shape

torch.Size([3, 3])

In [8]:
tensorA=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tensorB=torch.tensor([[10,11,12],
                      [13,14,15]])
mul=torch.matmul(tensorA,tensorB.T)
mul

tensor([[ 68,  86],
        [167, 212],
        [266, 338]])

In [33]:
# Min, Max, Mean, Sum, etc....
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
# Find Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [11]:
# Find Max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [12]:
# Find Mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # Convert to float 32 because mean dont run in Long type

(tensor(50.), tensor(50.))

In [13]:
# Find Sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

In [14]:
# Find location MIN/MAX
x.argmin(), x.argmax()

(tensor(0), tensor(10))

In [22]:
# Add extra dimension
x_reshaped=x.reshape(1,10)
x_reshaped2=x.reshape(2,5)
x_reshaped3=x.reshape(10,1)
print(x_reshaped)
print(x_reshaped2)
print(x_reshaped3)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])
tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])


In [34]:
# Change the view
z=x.view(10,1)
z

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [35]:
# Changing Z changes X (share memory)
z[:,-1]=5
x

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [36]:
# Squeeze (remove single dimension in all tensor)
x_sq=x.squeeze()
x_sq.shape

torch.Size([10])

In [44]:
# Unsqueeze (Add a single dimentsion to a target tensor)
print(f"tensor shape: {x_sq.shape}")
print(f"tensor : {x_sq.unsqueeze(dim=1).shape}")

tensor shape: torch.Size([10])
tensor : torch.Size([10, 1])


In [47]:
# Permute - rearange the tensor (view: share memory)
x=torch.rand(22,22,3)
per=x.permute(2,1,0)
per.shape

torch.Size([3, 22, 22])