### **Pytorch Fundamental**

In [32]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [33]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


## **Day 2**

In [10]:
#create random tensor
random_tensor=torch.rand(10,10)
random_tensor

tensor([[0.9733, 0.0801, 0.3447, 0.3709, 0.1533, 0.6518, 0.0293, 0.2791, 0.6486,
         0.9532],
        [0.9108, 0.1624, 0.9237, 0.4690, 0.8108, 0.2340, 0.2409, 0.1902, 0.4304,
         0.1709],
        [0.4321, 0.2482, 0.3776, 0.9389, 0.9967, 0.7429, 0.2680, 0.3744, 0.6312,
         0.8790],
        [0.0568, 0.3674, 0.1073, 0.4396, 0.3377, 0.6328, 0.9071, 0.9633, 0.2328,
         0.0594],
        [0.0401, 0.4830, 0.8854, 0.3460, 0.6533, 0.2788, 0.1336, 0.8160, 0.5906,
         0.7470],
        [0.6640, 0.7743, 0.6329, 0.4310, 0.2873, 0.0266, 0.5160, 0.0845, 0.4747,
         0.1145],
        [0.5901, 0.0604, 0.8011, 0.2395, 0.4076, 0.7639, 0.3970, 0.8272, 0.9410,
         0.6796],
        [0.1032, 0.3156, 0.7946, 0.5590, 0.9601, 0.5382, 0.5868, 0.1270, 0.8588,
         0.0322],
        [0.1482, 0.4691, 0.4048, 0.8635, 0.6013, 0.5769, 0.3767, 0.9175, 0.8499,
         0.1538],
        [0.2741, 0.2954, 0.7930, 0.6364, 0.6186, 0.1879, 0.2439, 0.7765, 0.3696,
         0.4789]])

In [11]:
random_image_size=torch.rand(size=(224,224,3))
random_image_size

tensor([[[0.5035, 0.7054, 0.5971],
         [0.0413, 0.9511, 0.9592],
         [0.9798, 0.6390, 0.8610],
         ...,
         [0.5644, 0.1387, 0.4080],
         [0.3820, 0.0837, 0.0759],
         [0.9364, 0.1211, 0.6717]],

        [[0.9886, 0.6246, 0.4577],
         [0.7775, 0.1386, 0.8818],
         [0.8321, 0.9354, 0.6158],
         ...,
         [0.4036, 0.1016, 0.6741],
         [0.2096, 0.9674, 0.1138],
         [0.0718, 0.2581, 0.5103]],

        [[0.6739, 0.2475, 0.5586],
         [0.4554, 0.8355, 0.7025],
         [0.5418, 0.3275, 0.4744],
         ...,
         [0.1824, 0.9944, 0.8184],
         [0.7083, 0.6879, 0.5734],
         [0.9117, 0.1398, 0.9021]],

        ...,

        [[0.8538, 0.4729, 0.2731],
         [0.5070, 0.8783, 0.3071],
         [0.4114, 0.6681, 0.4808],
         ...,
         [0.8527, 0.9266, 0.2348],
         [0.1421, 0.6928, 0.3494],
         [0.9180, 0.5167, 0.8410]],

        [[0.3331, 0.6430, 0.0792],
         [0.2537, 0.8576, 0.2860],
         [0.

In [12]:
#create zeros matrix
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#ones matrix
one=torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
#Range
zero_to_ten=torch.arange(start=0,end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#tensor_like
ten_zeros=torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#float32_tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor.dtype

torch.float32

In [24]:
float_16=float_32_tensor.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
mul=float_16*float_32_tensor
mul.dtype

torch.float32

In [30]:
int32=torch.tensor([3,6,9], dtype=torch.int32)
mul=int32*float_32_tensor
mul

tensor([ 9., 36., 81.])

In [49]:
# Manipulating Tensors

# Addittion
tensor=torch.tensor([1,2,3])
print(f"Add: {tensor+10}")
add=torch.add(tensor,10)
print(f"Add Function: {add}")

# Multiply Tensor
print(f"Multiply : {tensor*2}")
mul=torch.mul(tensor,10)
print(f"Multiply function: {mul}")

# Substract
print(f"Substract: {tensor-1}")
sub=torch.sub(tensor,1)
print(f"Sub Function: {sub}")

# Division
print(f"Division: {tensor/2}")
div=torch.div(tensor,2)
print(f"Division Function: {div}")

Add: tensor([11, 12, 13])
Add Function: tensor([11, 12, 13])
Multiply : tensor([2, 4, 6])
Multiply function: tensor([10, 20, 30])
Substract: tensor([0, 1, 2])
Sub Function: tensor([0, 1, 2])
Division: tensor([0.5000, 1.0000, 1.5000])
Division Function: tensor([0.5000, 1.0000, 1.5000])


In [55]:
# Slot Wise
print(tensor, "*", tensor)
print(f"Mul Slot Wise: {tensor*tensor}")

# Matrix Multiply
print(f"Multiply: {torch.matmul(tensor,tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Mul Slot Wise: tensor([1, 4, 9])
Multiply: 14
