### **Pytorch Fundamental**

In [1]:
!nvidia-smi

Thu Aug 15 15:32:50 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [5]:
scalar = torch.tensor(2)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

2

In [16]:
#vector
vector = torch.tensor([2,2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([2, 2])
1
torch.Size([2])


In [17]:
#matrix
matrix=torch.tensor([[1,2],
                     [3,4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [18]:
#tensor
tensor=torch.tensor([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [20]:
tensor[0][1]

tensor([4, 5, 6])